
services:
  lancedb:
    build: .
    container_name: lancedb-server
    ports:
      - "9014:9014"  # 映射端口，宿主机:容器
    volumes:
      - ./data:/data  # 关键：将本地 data 目录挂载到容器内 /data
      - ./src:/app
    environment:
      - TZ=Asia/Shanghai
    restart: always
    command: uvicorn main:lancedb --host 0.0.0.0 --port 9014 --reload
