FROM python:3.11-slim

WORKDIR /app

# 安装依赖 (lancedb + fastapi + uvicorn)
RUN pip install --no-cache-dir lancedb fastapi uvicorn pandas pydantic

#COPY ./src /app

# 暴露端口
EXPOSE 9014

# 启动命令
CMD ["python", "main.py"]
