# RTAB-Map RGB-D 模式配置 — 视觉特征 + ICP + Odom 辅助
rtabmap:
  ros__parameters:
    # ---- 坐标帧 ----
    frame_id: "base_footprint"
    odom_frame_id: "odom"
    subscribe_rgb: true
    subscribe_depth: true
    subscribe_odom: true
    subscribe_scan_cloud: false
    subscribe_scan: false
    subscribe_odom_info: false

    # ---- RGB-D 时间同步 ----
    approx_sync: true
    approx_sync_max_interval: 2.0
    topic_queue_size: 50
    sync_queue_size: 50
    odom_sensor_sync: false

    # ---- 视觉特征 ----
    Rtabmap/DetectionRate: "2"
    Vis/MinInliers: "10"
    Kp/MaxFeatures: "1000"
    Mem/UseOdomFeatures: "true"

    # ---- 栅格分辨率 ----
    Grid/CellSize: "0.05"

    # ---- TF ----
    publish_tf: true
    wait_for_transform: 30.0
    tf_tolerance: 30.0

    # ---- 深度图 ----
    depth_image_transport: "raw"

    # ---- 建图策略 ----
    Reg/Force3DoF: "true"
    Reg/Strategy: "0"

    # ---- 新节点创建 ----
    RGBD/ProximityBySpace: "true"
    RGBD/LinearUpdate: "0.2"
    RGBD/AngularUpdate: "0.2"
    RGBD/LocalRadius: "10.0"

    # ---- 栅格地图 ----
    RGBD/CreateOccupancyGrid: "true"
    Grid/Sensor: "1"
    Grid/FromDepth: "false"
    Grid/RangeMin: "0.3"
    Grid/RangeMax: "5.0"
    Grid/NormalsSegmentation: "true"   # 关法线(光心Y=下导致法线反向)
    Grid/MaxGroundHeight: "0.4"        # 地面容忍 0-40cm
#    Grid/FootprintHeight: "10.0"       # 地面以上10m≈不限
    map_filter_radius: 0.0
    map_filter_angle: 0.0
    map_always_update: true
    cloud_output_voxelized: false
